config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  namespace :components do
    resource :shopping_cart, only: [:show]
    resource :user_review, only: [:show]
    resource :bank_account, only: [:show]
    resource :build_log, only: [:show]
  end

  resource :shopping_cart, only: [:show, :create, :destroy]
  resources :user_reviews, only: [:index, :edit, :update, :create, :destroy]
  resource :bank_account, only: [:show] do
    patch :withdraw
    patch :deposit
    patch :toggle_lock
    patch :reset_logs
  end
  resource :build_log, only: [:show, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord

  before_create :load_free_bal

  validates :identifier, presence: true, uniqueness: true
  validates :balance, presence: true

  FREE_BALANCE = 2_000.freeze
  NO_LOG = "No logs for your bank account.".freeze

  def withdraw(amount)
    if locked?
      new_log = logs.to_s + "[#{Time.current.to_s}] Attempted to withdraw #{amount} but account is locked. \n"
      update(logs: new_log)
      return
    end

    with_lock do
      new_bal = (balance - amount)
      return if new_bal < 0

      if update(balance: new_bal)
        new_log = logs.to_s + "[#{Time.current.to_s}] Withdrew #{amount} successfully. \n"
        update(logs: new_log)
      end
    end
  end

  def deposit(amount)
    if locked?
      new_log = logs.to_s + "[#{Time.current.to_s}] Attempted to deposit #{amount} but account is locked. \n"
      update(logs: new_log)
      return
    end

    with_lock do
      new_bal = balance + amount

      if update(balance: new_bal)
        new_log = logs.to_s + "[#{Time.current.to_s}] Deposited #{amount} successfully. \n"
        update(logs: new_log)
      end
    end
  end

  def toggle_lock
    update(locked: !locked)
  end

  private

  def load_free_bal
    self.balance = FREE_BALANCE
  end

end

app/models/build_log.rb
class BuildLog < ApplicationRecord

  validates :identifier, presence: true, uniqueness: true

  NO_LOG = "No log whatsoever".freeze

  TEMPLATES = [
    "Initializing server... \n",
    "Copying files and templates.. \n",
    "Done",
  ].freeze

  def append(content)
    new_body = self.body.to_s + content
    update(body: new_body)
  end

end

app/models/cart.rb
class Cart < ApplicationRecord

  validates :identifier, presence: true, uniqueness: true

  has_many :line_items

  def add(product)
    line_item = line_items.find_by(product: product)

    if line_item
      line_item.increment!(:quantity)
    else
      line_items.create(product: product)
    end
  end

  def remove(product)
    line_item = line_items.find_by(product: product)
    return if line_item.nil?

    if line_item.quantity <= 1
      line_item.destroy
    else
      line_item.decrement!(:quantity)
    end
  end

  def total_price
    line_items.sum(&:subtotal)
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :cart
  belongs_to :product

  def subtotal
    quantity * product.price
  end

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user_review.rb
class UserReview < ApplicationRecord

  validates :author, :content, presence: true
  validates :rating, numericality: { in: 1..5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_cart
  before_action :set_bank_account
  before_action :set_build_log

  private

  def set_cart
    @cart ||= Cart.find_or_create_by(identifier: session.id.to_s)
  end

  def set_bank_account
    @bank_account ||= BankAccount.find_or_create_by(identifier: session.id.to_s)
  end

  def set_build_log
    @build_log ||= BuildLog.find_or_create_by(identifier: session.id.to_s)
  end

end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController

  def show
  end

  def withdraw
    @bank_account.withdraw(100)
  end

  def deposit
    @bank_account.deposit(100)
  end

  def toggle_lock
    @bank_account.toggle_lock
  end

  def reset_logs
    @bank_account.update(logs: nil)
  end

end

app/controllers/build_logs_controller.rb
class BuildLogsController < ApplicationController

  def show
  end

  def update
    RunLogJob.perform_now(@build_log.id, :clear)

    BuildLog::TEMPLATES.each_with_index do |template, idx|
      time_to_wait = (idx.to_i + 1) * 2
      RunLogJob.
        set(wait: time_to_wait.seconds).
        perform_later(@build_log.id, template)
    end

    head :no_content
  end

end

app/controllers/components/bank_accounts_controller.rb
module Components
  class BankAccountsController < ApplicationController

    def show
    end

  end
end

app/controllers/components/build_logs_controller.rb
module Components
  class BuildLogsController < ApplicationController

    def show
    end

  end
end

app/controllers/components/shopping_carts_controller.rb
module Components
  class ShoppingCartsController < ApplicationController

    def show
    end

  end
end

app/controllers/components/user_reviews_controller.rb
module Components
  class UserReviewsController < ApplicationController

    def show
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  def show
    @products = Product.all
  end

  def create
    @product = Product.find(params[:product_id])
    @cart.add(@product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @cart.remove(@product)
  end

end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController

  def index
    @reviews = UserReview.order(created_at: :desc)
  end

  def create
    @review = UserReview.new(user_review_params)
    @review.save!
  end

  def edit
    @review = UserReview.find(params[:id])
  end

  def update
    @review = UserReview.find(params[:id])
    @review.update(user_review_params)
  end

  def destroy
    @review = UserReview.find(params[:id])
    @review.destroy
  end

  private

  def user_review_params
    params.require(:user_review).permit(
      :author,
      :content,
      :rating,
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_accounts/_account.html.erb
<div class="border border-blue-500 rounded">
  <header class="text-center bg-blue-500 text-yellow-300 font-bold p-2 text-lg"> BANK ACCOUNT </header>

  <div class="p-2">
    <div class="mb-2">
      <span class="font-semibold text-lg"> BAL: <%= number_to_currency(@bank_account.balance, unit: "P") %> </span>
    </div>

    <div class="mb-4">
      <%= button_to "Withdraw", withdraw_bank_account_path, method: :patch, class: "border border-blue-500 rounded py-1 w-full mb-2 hover:bg-blue-500 hover:text-yellow-300" %>
      <%= button_to "Deposit", deposit_bank_account_path, method: :patch, class: "border border-blue-500 rounded py-1 w-full hover:bg-blue-500 hover:text-yellow-300" %>
    </div>

    <div class="flex flex-row-reverse">
      <%= button_to "#{@bank_account.locked? ? "locked" : "unlocked"}", toggle_lock_bank_account_path, method: :patch, class: "text-sm #{@bank_account.locked? ? "text-red-500" : "text-green-500"}" %>
    </div>
  </div>
</div>

app/views/bank_accounts/_logs.html.erb
<div class="h-48">
  <%= text_area_tag :logs, @bank_account.logs.to_s.split("\n").reverse.join("\n").presence || BankAccount::NO_LOG, class: "w-full h-full border rounded bg-gray-100 border-blue-500 text-xs" %>
</div>

app/views/bank_accounts/deposit.turbo_stream.erb
<%= turbo_stream.update(@bank_account, partial: "bank_accounts/account") %>
<%= turbo_stream.update(dom_id(@bank_account, :logs), partial: "bank_accounts/logs") %>

app/views/bank_accounts/reset_logs.turbo_stream.erb
<%= turbo_stream.update(dom_id(@bank_account, :logs), partial: "bank_accounts/logs") %>

app/views/bank_accounts/show.html.erb
<header class="font-semibold text-xl mb-4"> Bank Account </header>

<div class="flex">
  <div class="w-1/4 mr-2">
    <%= turbo_frame_tag @bank_account do %>
      <%= render "account" %>
    <% end %>
  </div>

  <div class="flex-1 border rounded">
    <div class="flex flex-row-reverse">
      <%= button_to "reset logs", reset_logs_bank_account_path, method: :patch, class: "text-red-500 text-xs px-2" %>
    </div>
    <div class="p-2">
      <%= turbo_frame_tag dom_id(@bank_account, :logs) do %>
        <%= render "logs" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bank_accounts/toggle_lock.turbo_stream.erb
<%= turbo_stream.update(@bank_account, partial: "bank_accounts/account") %>

app/views/bank_accounts/withdraw.turbo_stream.erb
<%= turbo_stream.update(@bank_account, partial: "bank_accounts/account") %>
<%= turbo_stream.update(dom_id(@bank_account, :logs), partial: "bank_accounts/logs") %>

app/views/build_logs/_body.html.erb
<%= text_area_tag :body, build_log.body.to_s.presence || BuildLog::NO_LOG, class: "bg-gray-100 border rounded w-full h-full text-xs" %>

app/views/build_logs/show.html.erb
<%= turbo_stream_from "build_logs" %>

<div class="h-96 mb-2">
  <%= turbo_frame_tag @build_log do %>
    <%= render "body", build_log: @build_log %>
  <% end %>
</div>

<div class="flex flex-row-reverse">
  <%= button_to "Run logs", build_log_path, method: :patch, class: "bg-blue-500 text-white p-2 border rounded" %>
</div>

app/views/home/index.html.erb
home

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HOTWIRE: Kitchen Sink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto p-2">
      <header class="text-2xl bg-black text-white rounded p-2 font-semibold mb-4"> 
        KITCHEN SINK (Hotwire components) 
      </header>

      <div class="flex">
        <div class="w-1/4 mr-2">
          <%= render "shared/sidebar" %>
        </div>

        <div class="flex-1 border rounded p-2">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/review/applies/_review.html.erb
<%= turbo_frame_tag review do %>
  <div class="border rounded p-2 mb-2 w-1/2">
    <div>
      <% review.rating.times do %>
        ⭐️
      <% end %>
    </div>

    <span class="text-lg"> <%= review.content %> </span>

    <div class="flex flex-row-reverse">
      <small> reviewed by: <%= review.author %> </small>
    </div>
  </div>
<% end %>

app/views/review/applies/_write_review.html.erb
<%= turbo_frame_tag :write_review do %>
  <details class="cursor-pointer">
    <summary> Write a review </summary>

    <div class="border rounded bg-white p-2 w-1/2">
      <%= form_with model: UserReview.new, url: add_review_apply_path do |f| %>
        <%= render "form", f: f %>
      <% end %>
    </div>
  </details>
<% end %>

app/views/review/applies/show.html.erb
<div class="mb-4">
  <header class="font-semibold text-xl"> User Reviews </header>
</div>

<div class="mb-4">
  <%= render "write_review" %>
</div>

<%= turbo_frame_tag :review_list do %>
  <% @reviews.each do |review| %>
    <%= render "review", review: review %>
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="border rounded divide-y">
  <div class="p-1"><%= link_to "home", root_path %></div>
  <div class="p-1"><%= link_to "shopping cart", components_shopping_cart_path %></div>
  <div class="p-1"><%= link_to "user reviews", components_user_review_path %></div>
  <div class="p-1"><%= link_to "bank withdrawal/deposit", components_bank_account_path %></div>
  <div class="p-1"><%= link_to "build logs (stream)", components_build_log_path %></div>
</nav>

app/views/shopping_cart/applies/_cart.html.erb
<%= turbo_frame_tag @cart do %>
  <div class="divide-y mb-4">
    <% @cart.line_items.each do |line_item| %>
      <div class="flex justify-between">
        <div class="flex">
          <span class="mr-2">
            <%= button_to "❌", remove_shopping_cart_apply_path(product_id: line_item.product_id), method: :delete, class: "text-xs" %>
          </span>
          <span class="bg-gray-100 text-black px-2 rounded mr-2"> <%= line_item.quantity %> </span>
          <span> <%= line_item.product.name %> </span>
        </div>

        <div> <%= number_to_currency(line_item.subtotal, unit: "P") %> </div>
      </div>
    <% end %>
  </div>

  <div class="flex flex-row-reverse">
    total: <%= number_to_currency(@cart.total_price, unit: "P") %>
  </div>
<% end %>

app/views/shopping_cart/applies/add.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: "cart") %>
<%= turbo_stream.update(dom_id(@cart, :number_of_items), @cart.line_items.sum(:quantity)) %>

app/views/shopping_cart/applies/remove.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: "cart") %>
<%= turbo_stream.update(dom_id(@cart, :number_of_items), @cart.line_items.sum(:quantity)) %>

app/views/shopping_cart/applies/show.html.erb
<div class="flex justify-between items-center mb-4">
  <header class="font-semibold text-xl"> Turbo Cart </header>

  <details class="relative cursor-pointer">
    <summary> 🛒 (<span id="<%= dom_id(@cart, :number_of_items) %>"><%= @cart.line_items.sum(:quantity) %></span>) </summary>

    <div class="absolute right-0 border rounded bg-gray-100 w-96 p-2">
      <%= render "cart" %>
    </div>
  </details>
</div>

<div class="grid grid-cols-6 gap-4">
  <% @products.each do |product| %>
    <%= button_to(add_shopping_cart_apply_path(product_id: product.id), method: :post) do %>
      <div class="border rounded">
        <%= image_tag product.image_url %>
        <div> <%= product.name %> </div>
        <div class="font-bold"> <%= number_to_currency(product.price, unit: "P") %> </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shopping_carts/_cart.html.erb
<%= turbo_frame_tag @cart do %>
  <div class="divide-y mb-4">
    <% @cart.line_items.each do |line_item| %>
      <div class="flex justify-between">
        <div class="flex">
          <span class="mr-2">
            <%= button_to "❌", shopping_cart_path(product_id: line_item.product_id), method: :delete, class: "text-xs" %>
          </span>
          <span class="bg-gray-100 text-black px-2 rounded mr-2"> <%= line_item.quantity %> </span>
          <span> <%= line_item.product.name %> </span>
        </div>

        <div> <%= number_to_currency(line_item.subtotal, unit: "P") %> </div>
      </div>
    <% end %>
  </div>

  <div class="flex flex-row-reverse">
    total: <%= number_to_currency(@cart.total_price, unit: "P") %>
  </div>
<% end %>

app/views/shopping_carts/create.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: "cart") %>
<%= turbo_stream.update(dom_id(@cart, :number_of_items), @cart.line_items.sum(:quantity)) %>

app/views/shopping_carts/destroy.turbo_stream.erb
<%= turbo_stream.update(@cart, partial: "cart") %>
<%= turbo_stream.update(dom_id(@cart, :number_of_items), @cart.line_items.sum(:quantity)) %>

app/views/shopping_carts/show.html.erb
<div class="flex justify-between items-center mb-4">
  <header class="font-semibold text-xl"> Turbo Cart </header>

  <details class="relative cursor-pointer">
    <summary> 🛒 (<span id="<%= dom_id(@cart, :number_of_items) %>"><%= @cart.line_items.sum(:quantity) %></span>) </summary>

    <div class="absolute right-0 border rounded bg-gray-100 w-96 p-2">
      <%= render "cart" %>
    </div>
  </details>
</div>

<div class="grid grid-cols-6 gap-4">
  <% @products.each do |product| %>
    <%= button_to(shopping_cart_path(product_id: product.id), method: :post) do %>
      <div class="border rounded">
        <%= image_tag product.image_url %>
        <div> <%= product.name %> </div>
        <div class="font-bold"> <%= number_to_currency(product.price, unit: "P") %> </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/user_reviews/_form.html.erb
<div>
  <%= f.text_field :author, class: "border rounded text-sm", placeholder: "Author" %>
</div>

<div>
  <%= f.text_area :content, class: "border rounded text-sm", placeholder: "Your review" %>
</div>

<div class="mb-2">
  <%= f.number_field :rating, class: "border rounded text-sm", placeholder: "Rating (1 to 5)" %>
</div>

<%= f.submit "Add review", class: "bg-blue-500 border rounded text-gray-100 p-2 cursor-pointer" %>

app/views/user_reviews/_review.html.erb
<%= turbo_frame_tag review do %>
  <div class="border rounded p-2 mb-2 w-1/2">
    <div class="flex justify-between items-center">
      <div>
        <% review.rating.times do %>
          ⭐️
        <% end %>
      </div>

      <div class="flex">
        <%= button_to "edit", edit_user_review_path(review), method: :get, class: "text-blue-500 text-sm mr-1" %>
        <%= button_to "delete", user_review_path(review), method: :delete, class: "text-red-500 text-sm" %>
      </div>
    </div>

    <span class="text-lg"> <%= review.content %> </span>

    <div class="flex flex-row-reverse">
      <small> reviewed by: <%= review.author %> </small>
    </div>
  </div>
<% end %>

app/views/user_reviews/_write_review.html.erb
<%= turbo_frame_tag :write_review do %>
  <details class="cursor-pointer">
    <summary> Write a review </summary>

    <div class="border rounded bg-white p-2 w-1/2">
      <%= form_with model: UserReview.new, url: user_reviews_path do |f| %>
        <%= render "form", f: f %>
      <% end %>
    </div>
  </details>
<% end %>

app/views/user_reviews/create.turbo_stream.erb
<%= turbo_stream.update(:write_review, partial: "user_reviews/write_review") %>
<%= turbo_stream.prepend(:review_list, partial: "user_reviews/review", locals: { review: @review }) %>

app/views/user_reviews/destroy.turbo_stream.erb
<%= turbo_stream.remove(@review) %>

app/views/user_reviews/edit.html.erb
<%= turbo_frame_tag @review do %>
  <%= form_with model: @review, url: user_review_path(@review) do |f| %>
    <div class="border rounded p-2 mb-2 w-1/2">
      <div class="flex justify-between items-center">
        <%= f.number_field :rating, class: "text-sm border rounded" %>

        <div class="flex">
          <%= button_to "update", user_review_path(@review), method: :patch, class: "text-blue-500 text-sm mr-1" %>
          <%= link_to "cancel", "#", class: "text-red-500 text-sm mr-1" %>
        </div>
      </div>

      <span class="text-lg"> 
        <%= f.text_area :content, class: "text-sm border rounded" %>
      </span>

      <div class="flex flex-row-reverse">
        <small> reviewed by: <%= @review.author %> </small>
      </div>
    </div>
  <% end %>
<% end %>

app/views/user_reviews/index.html.erb
<div class="mb-4">
  <header class="font-semibold text-xl"> User Reviews </header>
</div>

<div class="mb-4">
  <%= render "write_review" %>
</div>

<%= turbo_frame_tag :review_list do %>
  <% @reviews.each do |review| %>
    <%= render "review", review: review %>
  <% end %>
<% end %>

app/views/user_reviews/update.turbo_stream.erb
<%= turbo_stream.update(@review, partial: "user_reviews/review", locals: { review: @review }) %>